improve bin/e Emacs cli-starter
This variation is callable with or without file args, and will make emacs visible even if
it was previously hidden.

The `if [ $# -gt 0]` block that handles file args is run in the background (see the
closing `fi &`), but its contents run synchronously with respect to each other. That
prevents deleting the tempfiles before they've been visited, without resorting to `sleep`.

diff --git a/bin/e b/bin/e
--- a/bin/e
+++ b/bin/e
@@ -1,50 +1,28 @@
 #!/bin/sh
 
-exit_with_error() {
-  echo "$@" >&2
-  exit 1
-}
+emacs_app=/usr/local/opt/emacs-mac/Emacs.app
 
-emacs_app="/usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs"
-if [ ! -e $emacs_app ]; then
-  exit_with_error "Emacs.app not found"
+if [ ! -x $emacs_app ]; then
+  echo "Emacs.app not found" >&2
+  exit 1
 fi
 
-if [ ${#@} -eq 0 ]; then
-  $(/usr/bin/osascript <<-END
-    if application "Emacs.app" is running then
-      tell application id (id of application "Emacs.app") to activate
-    else
-      tell application "$emacs_app" to activate
-    end if
-END
-  ) &
-else
-  t=()
+/usr/bin/osascript -e "tell application \"$emacs_app\" to activate" &
+
+if [ $# -gt 0 ]; then
+  tempfiles=()
 
   while IFS= read -r filename; do
     if [ ! -f "$filename" ]; then
-      t+=("$filename") && /usr/bin/touch "$filename"
+      tempfiles+=("$filename")
+      /usr/bin/touch "$filename"
     fi
 
     file=$(echo $(cd $(dirname "$filename") && pwd -P)/$(basename "$filename"))
+    /usr/bin/osascript -e "tell application \"$emacs_app\" to open POSIX file \"$file\""
+  done <<< "$(printf '%s\n' "$@")"
 
-    $(/usr/bin/osascript <<-END
-      if application "Emacs.app" is running then
-        tell application id (id of application "Emacs.app") to open POSIX file "$file"
-      else
-        tell application "$emacs_app"
-          activate
-          open POSIX file "$file"
-        end tell
-      end if
-END
-    ) &
-  done <<<"$(printf '%s\n' "$@")"
-
-  if [ ! -z "$t" ]; then
-    $(/bin/sleep 10; for file in "${t[@]}"; do
-      [ ! -s "$file" ] && /bin/rm "$file";
-    done) &
-  fi
-fi
+  for tempfile in "${tempfiles[@]}"; do
+    [ ! -s "$tempfile" ] && /bin/rm "$tempfile"
+  done
+fi &
